### PR TITLE
Plot fixes

### LINKED ISSUE #7: Errors in "Simple example"
Hi, 

my name is Patrick and I am a student in Oded's course on parametric phenomena at the University of Constance. We got the possibility to try this Julia package and I found two minor errors in the "Simple example" on the code overview page when installing and testing it.

1. solutions = get_steady_states(**problem**, swept, fixed) gives: UndefVarError: "problem not defined"
-> **problem** should be changed to **harmonic_eq**

2. plot_1D_solutions(solutions, x="ω", y="sqrt(u1^2 + v1^2)"**]**); returns:  "syntax: unexpected "]" in argument list"
-> the closing bracket "**]**" should be removed

Fixing these errors will help future users to have a smoother start with the package (especially if they are not used to Julia as I was before). Thanks!

Best, 
Patrick

### PR DESCRIPTION
**Pull request by jkosata**
Closes #7 

Improved the legend in `plot_1D_solution`
Introduced custom keyword arguments to `plot_1D_solution` which are fed to matplotlib (examples: `markersize`, `color`)

Updated the version of `HomotopyContinuation` to 2.6.4

### CODE REVIEW

**Review by jdelpino — APPROVED** [review]

File: src/plotting_static.jl [hunk 1]
```diff
@@ -208,35 +205,40 @@ function plot_1D_solutions(res::Result; x::String, y::String, x_scale=1.0, y_sca
...
     end
 
     ax.set_xlabel(latexify(x),fontsize=24) 
     ax.set_ylabel(latexify(_prettify_label(res,y)),fontsize=24) 
 
     #legend preparation
-    ignored_idx = [all(isnan.(line.get_ydata())) for line in lines] #make up a legend with only non ignored entries in the plotter
+    ignored_idx = [all(isnan.(line.get_ydata())) for line in lines] # make up a legend with only non ignored entries in the plotter
     Nb   = sum(.~ignored_idx) #number of branches
-    leg1 = ax.legend(string.(collect(1:Nb)),ncol=(Nb<=col_length) + (Nb÷col_length + 1)*(Nb>col_length),
```
Comment (jdelpino) [inline src/plotting_static.jl:229]: The removal of the col_length argument implies legends will appear longer than the panels. I suggest to put it back as an option (see for example the action of plot_1D_solutions on the two parametrons example)

File: src/plotting_static.jl [hunk 2]
```diff
@@ -160,27 +160,26 @@ end
...
 
 Keyword arguments
 - `x`, `y`: Expressions to plot on as independent/dependent variables (parsed into Symbolics.jl).
-- `x_scale`, `y_scale`: Factors to multiply the shown axis ticks with.
 - `marker`: The point marker to use.
 - `xscale`, `yscale`: scale for x/y dimensions (e.g. "linear" or "log")
 - `plot_only`: a list of strings corresponding to the solution classes of `Result`. Only solutions which belong to the listed classes are plotted.
 - `marker_classification`: A class of the solutions (created by `classify_solutions!`) which is distinguished with different markers. Entering an inequality creates a new class "custom_class".
 - `filename`: if different from `nothing`, plotted data and parameter values are exported to `./filename.jld2`.
 - `col_length`: number of elements per legend column. By default 10.
```
Comment (jdelpino) [inline src/plotting_static.jl:176]: this argument has now been removed, although I suggest not doing so. See comment below

**Review by jdelpino — COMMENTED** [review]
It looks nice, but now there is no support for multiple legend columns. See comments in file

**Review by jdelpino — APPROVED** [review]
